# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.hostname = "nginx-test"
  config.vm.box = "chef/centos-6.6"
  config.vm.network "private_network", ip: "192.168.56.66"

  config.vm.provision "ansible" do |ansible|
  	ansible.playbook = "ansible/playbook.yml"
  	ansible.sudo = true
  	ansible.verbose = "v"
  end

  config.vm.synced_folder "/Users/user/Development/mt/", "/var/code"

end

